[package]
name = "perona-memory"
description = ""
version = "0.1.0"
edition = "2024"
exclude = ["/target"]

[dependencies]
proc_mem = "0.1.6"
serde = { version = "1", features = ["derive"] }
perona-types = { path = "../types", version = "0.1.0" }
